---
title: "R-i lühikursus"
author: "Risto Hinno"
date: "12. jaanuar 2019"
output: html_document
---
## Kursuse ülevaade

Käsitletavad teemad:

 - [rstudio](0.0_rstudio)
 - [andmetüübid](1.1_andmet%C3%BC%C3%BCbid)
 - [tingimuslause, tsükkel ja funktsioon](1.2_tingimuslause_tsykkel)
 - [paketid](1.3_paketid)
 - [aeg](1.4_aeg)
 - [andmete sisselugemine](2.1_andmete_lugemine)
 - [andmete töötlemine](2.2_andmete_tootlemine)
 - [graafikud](3.1_graafikud)
 - [raportite tegemine](3.2_raportid)
 - [koodi jagamine, hea koodi põhimõtteid](4.0_kood)
 - [masinõpe](5.0_masinope)
 
Kõiki teemasid ei jõua loengutes põhjalikult käsitleda, selleks käesoleva veebimaterjal, mis võiks aidata ise pusimisele kaasa.

## R-st

R on integreeritud tarkvarakomplekt andmete töötlemiseks, arvutamiseks ja graafiliseks kujutamiseks.
Riga saab:

  - andmeid töödelda, salvestada
  - teha maatriksarvutusi
  - luua masinõppemudeleid
  - luua (interaktiivseid) graafikuid (https://shiny.rstudio.com/gallery/,
  http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
  - teha raporteid (nt https://rpubs.com/RRisto)
  - lihtsamaid veebirakendusi (nt https://shiny.rstudio.com/gallery/,
  https://ristohinno.shinyapps.io/Riigiteenused_dashboard/)
  - ja palju muud
      
Plussid:

  - tasuta
  - suur kogukond -> lihtne abi saada
  - võimaldab teha taasesitatavat (reproducible) analüüsi 
  - dünaamiline, palju võimalusi (suure tõenäosusega on keegi sinu vajaduse jaoks juba paketi kirjutanud)
    
Miinused:

  - nõuab veidi vaeva õppimiseks
  - töötab operatiivmälu pealt -> piirang andmemahule (kuigi sellele on lahendusi)
    

### Abi leidmine

Kindlasti jõuad kohe kursuse alguses kohta, kus oleks vaja abi (ei oska teha, kood ei tööta jne). See on täiesti normaalne. Abi saamiseks soovitan kasutada alljärgnevaid ressursse:

 - google
 - Rstudio ("Help" tab all paremal)
 - help("funktsiooni nimi")
 - ?funktsiooni nimi
 - veeb (https://stackoverflow.com/, https://cran.r-project.org/, https://www.rstudio.com/resources/cheatsheets/)
 
### Õppimine

See siin pole kindlasti isegi mitte täielik ülevaade Rist. Kuid annab sulle teeotsa kätte. Ma luban, et sul on raske. Nagu meil kõigil, kes on programmeerimist õppinud. Trikk on mitte alla anda ja teha õppimine endale "söödavateks" tükkideks. 

Kuidas õppida?

- __proovi koodi kirjutada ilma kuskilt abi otsimata__. Kui jääd hätta, spikerda. Nii saad teada, mida sa veel ei oska (mõni funktsioon, põhimõte vms). Proovi nii mitu korda (nt 1x-2x päevas) ning üllatud varsti, et asjad hakkavad ise välja tulema.
- asjad, mis on ebaselged, pole meeles, kuid, mida oleks vaja teada. Tee nende kohta __mõttekaardid__ ja korda, kui mõni vaba hetk on. Ise kasutan appi: https://apps.ankiweb.net/. 10 min päevas ning sa üllatud kui kiiresti sa asjad selgeks saad. Pähe tuupimine pole eesmärk, kuid baasfunktsioonid, ja -tõed peaksid olema peas. See teeb suu palju kiiremaks ning võimaldab omandada juba keerukamat infot.
- kui sa ei usu, et sinu aju suudab seda õppida, __loe läbi raamat__: https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra/dp/039916524X ja põhjenda, mis sinus nii erilist on, et ei suuda Ri õppida

Kui on abi vaja, siis alusta ülaltoodud abi leidmise viisidest. Kui jääd hätta, võid ka minu käest küsida. Kirjuta mure siia: https://github.com/RRisto/RRisto.github.io/issues (palun pane nii selge pealkiri kui oskad) ning pane kaasa minimaalne koodiosa (kui küsimus on konkreetse näitega seotud) koos andmetega, et saaksin sinu viga/mure luua. Kui sul githubi kontot pole, siis kirjuta e-kiri ristohinno@gmail.com (lisa sama info, mis oleks ka githubis). Kui postitad sinna, siis näevad sinu küsimust ka teised ning saavad samuti abi.


## Veel materjale/abivahendeid R-i õppimiseks

- Swirl, on interaktiivne pakett, mis õpetab Ri kasutama. installi pakett "swirl" koos sobiva kursusega. Juhend selle kohta on siin: https://swirlstats.com/students.html Käsud on sellised:

    - install.packages("swirl") #paketi pead ainult korra installima
    - library(swirl)
    - install_course("kursuse nimi") #kursuse nimi tuleb asendada tegeliku kursuse nimega, nimed on siin: https://github.com/swirldev/swirl_courses#swirl-courses
    - swirl()
    
- online kursused. Neid võib leida näiteks https://www.coursera.org lehelt. 

    - Ise julgen soovitada: https://www.coursera.org/specializations/jhu-data-science (otseselt Ri programmeerimise kohta on see osa: https://www.coursera.org/learn/r-programming kuid kogu kursuse vältel toimub tegevus Ris).
    - Datacamp: https://www.datacamp.com/courses/free-introduction-to-r
    - edX: https://www.edx.org/course/introduction-r-data-science-3
    
Õppimise seisukohalt soovitan võtta üks kursus ja proovida see läbi teha (ei ole mõtet kursust pooleli jätta, lootes, et kuskil on veel parem kursus). Samuti on väga efektiivne õppevorm leida mõni eluline probleem, mida tahaksid Riga lahendada (nt teha analüüs, raport) ning hakata seda tegema. Kui mingi koht tundub keeruline, siis otsida konkreetse teema kohta materjali.


        